feat: Minimal VERBOSE mode implementation - set -x debugging only
- Added -v and -vv flag parsing in env-variables
- -v sets VERBOSE=1
- -vv sets VERBOSE=2 and enables 'set -x' for bash debugging
- Implemented argument validation for -e, -s, -d flags
- Sanitized environment names in ssh-utils to prevent variable name errors
- Export VERBOSE to remote SSH sessions for remote debugging
- Code cleanup: removed extra blank lines, removed bats-assert/support dependencies

Closes #78
Closes #82

diff --git a/env-variables b/env-variables
--- a/env-variables
+++ b/env-variables
@@ -92,6 +92,10 @@ for (( i=1; i <= "$#"; i++ )); do
             ;;
         -e|-s|--source|--environment)
             j=$(($i+1))
+            if [[ -z "${!j:-}" ]] || [[ "${!j}" =~ ^- ]]; then
+                printf "\033[31mError: Option %s requires an argument.\033[0m\n" "${!i}" >&2
+                exit 1
+            fi
             ENV_SOURCE="${!j}"
             SKIP_INDICES+=($i $j)
             ;;
@@ -101,16 +105,33 @@ for (( i=1; i <= "$#"; i++ )); do
             ;;
         -d|--destination)
             j=$(($i+1))
+            if [[ -z "${!j:-}" ]] || [[ "${!j}" =~ ^- ]]; then
+                printf "\033[31mError: Option %s requires an argument.\033[0m\n" "${!i}" >&2
+                exit 1
+            fi
             ENV_DESTINATION="${!j}"
             SKIP_INDICES+=($i $j)
             ;;
         -v|--verbose)
-            export VERBOSE=1
-            export VERBOSE_FLAG="-v"
+            export VERBOSE=$((VERBOSE + 1))
+            SKIP_INDICES+=($i)
+            ;;
+        -vv)
+            export VERBOSE=$((VERBOSE + 2))
             SKIP_INDICES+=($i)
             ;;
     esac
 done
+
+# Set VERBOSE_FLAG and debug mode based on cumulative verbosity
+if [[ "${VERBOSE}" -ge 2 ]]; then
+    export VERBOSE_FLAG="-vv"
+    set -x
+elif [[ "${VERBOSE}" -eq 1 ]]; then
+    export VERBOSE_FLAG="-v"
+else
+    export VERBOSE_FLAG=""
+fi
 
 # Build filtered args (excluding source/destination flags)
 for (( i=1; i <= "$#"; i++ )); do
